### ISSUE TITLE
Module version mismatch. Expected 48, got 51

### ISSUE THREAD

**Issue by barathank** [mongodb-js/kerberos#59]
We are trying to build kerberos in NodeJS v7.4 which worked great but when executing the code we are receiving following error, Please help.

module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/node_modules/kerberos/lib/kerberos.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by christkv** [comment]
The code is compiled with a different node versions than what you are running it with.

**Comment by barathank** [comment]
Thanks @christkv, this issue is resolved.
