### ISSUE TITLE
Unable to install 1.0.0 on node 10.9 - prebuild-install || node-gyp rebuild

### ISSUE THREAD

**Issue by rjdjohnston** [mongodb-js/kerberos#85]
Here is my log:

```
> [root@session-manager]# sudo npm install kerberos                       
> > kerberos@1.0.0 install /home/nodejsAdmin/session-manager/node_modules/kerberos
> > prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21      ' not found (required by /home/nodejsAdmin/session-manager/node_modules/kerberos      /build/Release/kerberos.node)
> make: Entering directory `/home/nodejsAdmin/session-manager/node_modules/kerbero      s/build'
>   CXX(target) Release/obj.target/kerberos/src/kerberos.o
> In file included from ../src/kerberos.h:4,
>                  from ../src/kerberos.cc:1:
> ../../nan/nan.h:47:3: error: #error This version of node/NAN/v8 requires a C++11       compiler
> In file included from /root/.node-gyp/6.14.4/include/node/node.h:42,
>                  from ../../nan/nan.h:51,
>                  from ../src/kerberos.h:4,
>                  from ../src/kerberos.cc:1:
> /root/.node-gyp/6.14.4/include/node/v8.h:345: error: expected unqualified-id bef      ore ‘using’
> /root/.node-gyp/6.14.4/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::May      beLocal()’:
> /root/.node-gyp/6.14.4/include/node/v8.h:362: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘bool v8::MaybeLoca      l<T>::IsEmpty() const’:
> /root/.node-gyp/6.14.4/include/node/v8.h:369: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘bool v8::MaybeLoca      l<T>::ToLocal(v8::Local<S>*) const’:
> /root/.node-gyp/6.14.4/include/node/v8.h:373: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘bool v8::WeakCallb      ackInfo<T>::IsFirstPass() const’:
> /root/.node-gyp/6.14.4/include/node/v8.h:441: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: At global scope:
> /root/.node-gyp/6.14.4/include/node/v8.h:481: error: expected unqualified-id bef      ore ‘using’
> /root/.node-gyp/6.14.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global(      )’:
> /root/.node-gyp/6.14.4/include/node/v8.h:820: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global(      v8::Global<T>&&)’:
> /root/.node-gyp/6.14.4/include/node/v8.h:845: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘v8::Global<T>& v8:      :Global<T>::operator=(v8::Global<S>&&)’:
> /root/.node-gyp/6.14.4/include/node/v8.h:857: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: At global scope:
> /root/.node-gyp/6.14.4/include/node/v8.h:882: error: expected unqualified-id bef      ore ‘using’
> /root/.node-gyp/6.14.4/include/node/v8.h:1119: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h:1125: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘v8::MaybeLocal<v8:      :Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
> /root/.node-gyp/6.14.4/include/node/v8.h:3279: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: At global scope:
> /root/.node-gyp/6.14.4/include/node/v8.h:4499: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h:4515: error: ‘nullptr’ was not declared       in this scope
> /root/.node-gyp/6.14.4/include/node/v8.h: In member function ‘v8::Local<T> v8::M      aybeLocal<T>::ToLocalChecked()’:
> /root/.node-gyp/6.14.4/include/node/v8.h:7544: error: ‘nullptr’ was not declared       in this scope
> In file included from ../../nan/nan.h:197,
>                  from ../src/kerberos.h:4,
>                  from ../src/kerberos.cc:1:
> ../../nan/nan_maybe_43_inl.h: At global scope:
> ../../nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
> ../../nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
> ../../nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:29: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:37: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:45: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:52: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:71: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:79: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:87: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:96: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:130: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:147: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:173: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:196: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:203: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:211: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:226: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:234: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:242: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:250: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:258: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:266: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:276: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:286: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:298: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:309: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:316: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:322: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:328: error: expected initializer before ‘<’ token
> ../../nan/nan_maybe_43_inl.h:334: error: expected initializer before ‘<’ token
> ../src/kerberos.cc:150: error: expected ‘}’ at end of input
> ../../nan/nan_callbacks_12_inl.h:167: warning: ‘void Nan::imp::FunctionCallbackW      rapper(const v8::FunctionCallbackInfo<v8::Value>&)’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:181: warning: ‘void Nan::imp::GetterCallbackWra      pper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ defined b      ut not used
> ../../nan/nan_callbacks_12_inl.h:197: warning: ‘void Nan::imp::SetterCallbackWra      pper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v      oid>&)’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:253: warning: ‘void Nan::imp::PropertyGetterCal      lbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)’ d      efined but not used
> ../../nan/nan_callbacks_12_inl.h:270: warning: ‘void Nan::imp::PropertySetterCal      lbackWrapper(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallba      ckInfo<v8::Value>&)’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:290: warning: ‘void Nan::imp::PropertyEnumerato      rCallbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not us      ed
> ../../nan/nan_callbacks_12_inl.h:306: warning: ‘void Nan::imp::PropertyDeleterCa      llbackWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Boolean>&)      ’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:323: warning: ‘void Nan::imp::PropertyQueryCall      backWrapper(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Integer>&)’       defined but not used
> ../../nan/nan_callbacks_12_inl.h:428: warning: ‘void Nan::imp::IndexGetterCallba      ckWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Value>&)’ defined but not       used
> ../../nan/nan_callbacks_12_inl.h:444: warning: ‘void Nan::imp::IndexSetterCallba      ckWrapper(uint32_t, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<v8::Val      ue>&)’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:464: warning: ‘void Nan::imp::IndexEnumeratorCa      llbackWrapper(const v8::PropertyCallbackInfo<v8::Array>&)’ defined but not used
> ../../nan/nan_callbacks_12_inl.h:480: warning: ‘void Nan::imp::IndexDeleterCallb      ackWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Boolean>&)’ defined but       not used
> ../../nan/nan_callbacks_12_inl.h:496: warning: ‘void Nan::imp::IndexQueryCallbac      kWrapper(uint32_t, const v8::PropertyCallbackInfo<v8::Integer>&)’ defined but no      t used
> make: *** [Release/obj.target/kerberos/src/kerberos.o] Error 1
> make: Leaving directory `/home/nodejsAdmin/session-manager/node_modules/kerberos      /build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module      s/node-gyp/lib/build.js:276:23)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces      s.js:219:12)
> gyp ERR! System Linux 2.6.32-754.3.5.el6.x86_64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy      p/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/nodejsAdmin/session-manager/node_modules/kerberos
> gyp ERR! node -v v6.14.4
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> npm ERR! Linux 2.6.32-754.3.5.el6.x86_64
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "kerberos"
> npm ERR! node v6.14.4
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! kerberos@1.0.0 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the kerberos@1.0.0 install script 'prebuild-install || node-g      yp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the kerberos package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     prebuild-install || node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs kerberos
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls kerberos
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/nodejsAdmin/session-manager/npm-debug.log
>
```

I do have a c++ compiler installed:

```
[root@session-manager]# sudo yum install gcc-c++ make
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos, security
Setting up Install Process
Package gcc-c++-4.4.7-23.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Nothing to do
```

Any suggestions?

**Comment by mbroadst** [comment]
@rjdjohnston could you be facing a problem similar to this issue: https://github.com/nodejs/docker-node/issues/259. Otherwise, can you provide more info about what platform, os (distro), etc you are using?

**Comment by thecodejack** [comment]
@mbroadst Any migration guide from v0.0.24 to v1...seems like lot changes like following are unavailable

```
kerberos.authGSSClientInit(serviceName, 0, (err, ctx)
  kerberos.authGSSClientStep(ctx, '', (error)
  kerberos.authGSSClientClean(ctx, ()
```

**Comment by mbroadst** [comment]
@thecodejack the API has completely changed in v1.0.0, please see the README for the updated API.
